version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 27.3.1
          docker_layer_caching: true

      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push-image: true
          region: '${AWS_REGION}'
          repo: demo
          registry-id: '${AWS_ECR_REGISTRY_ID}'
          repo-scan-on-push: true
          tag: latest

  continuous-delivery:
    machine: true
    resource_class: jatin/nerrunner
    steps:
      - aws-cli/setup

      - run:
          name: Start Docker Service
          command: |
            sudo service docker start

      - run:
          name: auth to aws ecr
          command: aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin 022499021177.dkr.ecr.${AWS_REGION}.amazonaws.com

      - run:
          name: pull image from private repository
          command: sudo docker pull 022499021177.dkr.ecr.${AWS_REGION}.amazonaws.com/demo:latest

      - run:
          name: run image
          command: sudo docker run -d -p 8080:8080 022499021177.dkr.ecr.${AWS_REGION}.amazonaws.com/demo:latest

workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
          - continuous-integration
